name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Run tests (optional)
        run: |
          pnpm run test:run || echo "⚠️ Tests fallaron, pero continuamos con el deploy"
        continue-on-error: true

      - name: Run linting (optional)
        run: |
          pnpm run lint || echo "⚠️ Linting encontró warnings, pero continuamos con el deploy"
        continue-on-error: true

      - name: Build project
        run: pnpm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mundero-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mundero-build
          path: dist/

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
